"""Terrain check for ground sites, using DCS's own land data.

Claude places sites by bearing and distance, which can land a battery in a lake, a town or on a
hillside. Before spawning, the bridge asks DCS (through a Lua file run by Olympus) about a ring of
candidate spots around each planned site: surface type, how flat the footprint is, and how many
buildings or trees stand on it. It then moves each site to the nearest good spot.

If Olympus cannot run the probe (executeFile missing, or no answer in time), sites stay where
Claude put them and a warning is logged.
"""

from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

from .olympus import OlympusClient

log = logging.getLogger(__name__)

# Candidate spots around each planned site: (distance m, bearing deg). The planned spot comes first.
RINGS_M = (250, 500, 800)
OFFSETS = [(0, 0)] + [(d, b) for d in RINGS_M for b in range(0, 360, 45)]

MAX_SLOPE = 0.08  # height difference across the footprint / footprint width
MAX_OBSTACLES = 0

LUA = """-- Generated by the Red Commander bridge: terrain probe. Safe to delete.
local key = "{key}"
local sites = {{ {sites} }}
local offsets = {{ {offsets} }}
local ok_surface = {{ [land.SurfaceType.LAND] = true, [land.SurfaceType.ROAD] = true }}
local out = {{}}
for _, s in ipairs(sites) do
  local c = coord.LLtoLO(s[2], s[3], 0)
  for _, o in ipairs(offsets) do
    local x = c.x + o[1] * math.cos(math.rad(o[2]))
    local z = c.z + o[1] * math.sin(math.rad(o[2]))
    local r = s[4]
    local bad, hmin, hmax = 0, 1e9, -1e9
    for _, p in ipairs({{ {{0, 0}}, {{r, 0}}, {{-r, 0}}, {{0, r}}, {{0, -r}} }}) do
      local v = {{ x = x + p[1], y = z + p[2] }}
      if not ok_surface[land.getSurfaceType(v)] then bad = bad + 1 end
      local h = land.getHeight(v)
      if h < hmin then hmin = h end
      if h > hmax then hmax = h end
    end
    local obstacles = 0
    local volume = {{ id = world.VolumeType.SPHERE, params = {{ point = {{ x = x, y = land.getHeight({{ x = x, y = z }}), z = z }}, radius = r }} }}
    world.searchObjects(Object.Category.SCENERY, volume, function() obstacles = obstacles + 1 return true end)
    local lat, lng = coord.LOtoLL({{ x = x, y = 0, z = z }})
    out[#out + 1] = string.format("%d,%.6f,%.6f,%d,%.4f,%d", s[1], lat, lng, bad, (hmax - hmin) / (2 * r), obstacles)
  end
end
Olympus.executionResults[key] = table.concat(out, ";")
"""


@dataclass
class SiteRequest:
    id: int
    lat: float
    lng: float
    footprint_m: float  # radius that must be dry, flat and clear


@dataclass
class Sample:
    id: int
    lat: float
    lng: float
    wet_points: int  # footprint points on water or runway (0 to 5)
    slope: float
    obstacles: int
    index: int  # position in OFFSETS: 0 is the planned spot, higher is further away

    @property
    def good(self) -> bool:
        return self.wet_points == 0 and self.slope <= MAX_SLOPE and self.obstacles <= MAX_OBSTACLES

    def penalty(self) -> float:
        return self.wet_points * 100 + max(0.0, self.slope - MAX_SLOPE) * 200 + self.obstacles * 2 + self.index * 0.01


def build_lua(key: str, sites: list[SiteRequest]) -> str:
    site_rows = ", ".join(f"{{{s.id}, {s.lat:.6f}, {s.lng:.6f}, {s.footprint_m:.0f}}}" for s in sites)
    offset_rows = ", ".join(f"{{{d}, {b}}}" for d, b in OFFSETS)
    return LUA.format(key=key, sites=site_rows, offsets=offset_rows)


def parse(result: str) -> dict[int, list[Sample]]:
    samples: dict[int, list[Sample]] = {}
    for row in filter(None, result.split(";")):
        sid, lat, lng, wet, slope, obstacles = row.split(",")
        group = samples.setdefault(int(sid), [])
        group.append(Sample(int(sid), float(lat), float(lng), int(wet), float(slope), int(obstacles), len(group)))
    return samples


def choose(samples: list[Sample]) -> Sample:
    """The planned spot if it is good, else the nearest good one, else the least bad."""
    good = [s for s in samples if s.good]
    if good:
        return min(good, key=lambda s: s.index)
    return min(samples, key=Sample.penalty)


def probe(client: OlympusClient, sites: list[SiteRequest], work_dir: Path, timeout: float = 20.0) -> dict[int, list[Sample]] | None:
    """Run the probe in DCS. Returns None if Olympus gives no answer."""
    key = "redcmd-terrain-" + uuid.uuid4().hex[:12]
    work_dir.mkdir(parents=True, exist_ok=True)
    path = work_dir / "terrain-probe.lua"
    path.write_text(build_lua(key, sites), encoding="utf-8")
    try:
        client.execute_file(path)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            result = client.command_result(key)
            if isinstance(result, str) and result:
                return parse(result)
            time.sleep(1.0)
    except Exception as exc:
        log.warning("Terrain probe failed (%s); sites stay where planned.", exc)
        return None
    log.warning("Olympus did not answer the terrain probe within %.0fs; sites stay where planned. "
                "Check Saved Games/DCS/Logs/Olympus_log.txt for a Lua error.", timeout)
    return None
